"""
File: scripts/codegen/generate_event_schemas.py
Purpose: Generate the frontend SSE event contract (events.json + .ts) from WIRE_SCHEMA.
Category: tooling / codegen
Scope: Phase 57 / Sprint 57.67 (A-5b — event schema codegen)

Description:
    Reads the declarative single-source `WIRE_SCHEMA` + `BASE_FIELDS` from
    `backend/src/api/v1/chat/event_wire_schema.py` (loaded by file path via
    `importlib.util.spec_from_file_location` — NOT a package import, so this
    runs without installing the backend package) and emits two deterministic,
    repo-root-relative artifacts:

      1. frontend/src/features/chat_v2/generated/events.json
         Canonical snapshot: {"wire_types": [...sorted], "events": {...}}.
      2. frontend/src/features/chat_v2/generated/loopEvents.generated.ts
         Per-wire-type `export interface <Pascal>Event { type; data: {...} }`
         + the `LLMToolCall` element type + `export type LoopEvent` union +
         `export const KNOWN_LOOP_EVENT_TYPES` set.

    Wire shape note (Stage 2 reconciliation, Sprint 57.67): the SSE serializer
    (`sse.py:serialize_loop_event`) emits the NESTED shape
    `{ "type": ..., "data": { ...event-fields..., "trace_id": ... } }` — every
    event field (and the universal `trace_id`) lives INSIDE `data`. The store
    reducer (`chat_v2/store/chatStore.ts`) reads `ev.data.<field>`. The codegen
    therefore emits each event as `interface X { type; data: { ...fields } }`,
    NOT a flat field list. `trace_id` is emitted OPTIONAL (`trace_id?:`) inside
    `data` because the wire carries it but in-process consumers / fixtures
    construct events without it (it is correlation metadata the UI never reads).

    No-arg mode writes the files. `--check` mode regenerates in-memory and
    diffs against the committed files (line-ending-normalized both sides),
    printing a unified diff + exiting 1 on any mismatch (CI lint use). Output
    is deterministic + cross-platform: explicit `\\n` line endings, single
    trailing newline, sorted wire-types in events.json, declared field order in
    interfaces. Running twice produces zero git diff.

    PURE STDLIB. LLM-neutral (no SDK imports).

Key Components:
    - load_wire_schema(): file-path import of the registry module.
    - render_events_json() / render_generated_ts(): pure string builders.
    - main(): no-arg write vs `--check` diff modes.

Created: 2026-06-02 (Sprint 57.67)
Last Modified: 2026-06-03

Modification History (newest-first):
    - 2026-06-09: Sprint 57.96 — map subagent_child → SubagentChildEvent (Cat 11 Scope B)
    - 2026-06-03: Sprint 57.75 A-5c — map span_started/span_ended/memory_accessed → *Event types
    - 2026-06-02: Sprint 57.68 A-3b — map agent_handoff → AgentHandoffEvent (Cat 11 HANDOFF)
    - 2026-06-02: Initial creation (Sprint 57.67 A-5b) — wire-schema → FE artifact codegen

Related:
    - backend/src/api/v1/chat/event_wire_schema.py (single-source registry)
    - frontend/src/features/chat_v2/types.ts (Stage 2 re-exports the generated types)
    - .claude/rules/sprint-workflow.md (Step 2.5 codegen --check lint, Stage 2)
"""

from __future__ import annotations

import argparse
import difflib
import importlib.util
import json
import sys
from pathlib import Path
from types import ModuleType

# Repo root: scripts/codegen/generate_event_schemas.py → parents[2] = repo root.
REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_MODULE_PATH = (
    REPO_ROOT / "backend" / "src" / "api" / "v1" / "chat" / "event_wire_schema.py"
)
GENERATED_DIR = REPO_ROOT / "frontend" / "src" / "features" / "chat_v2" / "generated"
EVENTS_JSON_PATH = GENERATED_DIR / "events.json"
GENERATED_TS_PATH = GENERATED_DIR / "loopEvents.generated.ts"

GENERATED_HEADER = (
    "// AUTO-GENERATED by scripts/codegen/generate_event_schemas.py — DO NOT EDIT."
)

# Wire-type → TS interface name. AUTHORITATIVE from types.ts (Sprint 57.66 set):
# naive PascalCase would mangle acronyms (llm_request → "Llm..."), so this is an
# explicit map. The interface name MUST equal the current interface name in
# types.ts so Stage 2's re-export swap is a no-op rename.
WIRE_TYPE_TO_INTERFACE: dict[str, str] = {
    "loop_start": "LoopStartEvent",
    "turn_start": "TurnStartEvent",
    "llm_request": "LLMRequestEvent",
    "llm_response": "LLMResponseEvent",
    "tool_call_request": "ToolCallRequestEvent",
    "tool_call_result": "ToolCallResultEvent",
    "loop_end": "LoopEndEvent",
    "approval_requested": "ApprovalRequestedEvent",
    "approval_received": "ApprovalReceivedEvent",
    "guardrail_triggered": "GuardrailTriggeredEvent",
    "tripwire_triggered": "TripwireTriggeredEvent",
    "verification_passed": "VerificationPassedEvent",
    "verification_failed": "VerificationFailedEvent",
    "subagent_spawned": "SubagentSpawnedEvent",
    "subagent_completed": "SubagentCompletedEvent",
    "subagent_child": "SubagentChildEvent",
    "context_compacted": "ContextCompactedEvent",
    "prompt_built": "PromptBuiltEvent",
    "state_checkpointed": "StateCheckpointedEvent",
    "agent_handoff": "AgentHandoffEvent",
    "span_started": "SpanStartedEvent",
    "span_ended": "SpanEndedEvent",
    "memory_accessed": "MemoryAccessedEvent",
    "message_injected": "MessageInjectedEvent",
    "loop_terminated": "LoopTerminatedEvent",
}


def load_wire_schema() -> ModuleType:
    """Load event_wire_schema.py by file path (no backend package install needed)."""
    spec = importlib.util.spec_from_file_location(
        "event_wire_schema", SCHEMA_MODULE_PATH
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load wire-schema module at {SCHEMA_MODULE_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render_events_json(module: ModuleType) -> str:
    """Build the canonical events.json snapshot string (sorted wire-types)."""
    wire_schema: dict[str, dict[str, str]] = module.WIRE_SCHEMA
    snapshot = {
        "wire_types": sorted(wire_schema.keys()),
        "events": {
            wire_type: dict(fields) for wire_type, fields in wire_schema.items()
        },
    }
    # indent=2 for human-diffable JSON; explicit "\n" trailing newline added below.
    return json.dumps(snapshot, indent=2, ensure_ascii=False) + "\n"


def _pascal_interface(wire_type: str) -> str:
    """Resolve the authoritative TS interface name for a wire-type."""
    try:
        return WIRE_TYPE_TO_INTERFACE[wire_type]
    except KeyError as exc:  # pragma: no cover - guarded by the parity check below
        raise RuntimeError(
            f"No interface name mapped for wire-type {wire_type!r}; "
            "update WIRE_TYPE_TO_INTERFACE in generate_event_schemas.py."
        ) from exc


def render_generated_ts(module: ModuleType) -> str:
    """Build the loopEvents.generated.ts source string."""
    wire_schema: dict[str, dict[str, str]] = module.WIRE_SCHEMA
    base_fields: dict[str, str] = module.BASE_FIELDS
    tool_call_type_name: str = module.TOOL_CALL_ELEMENT_TYPE_NAME
    tool_call_fields: dict[str, str] = module.TOOL_CALL_ELEMENT_FIELDS

    # Validate every TS type string (pragmatic typo guard) before emitting.
    for fields in wire_schema.values():
        for ts_type in fields.values():
            module.validate_ts_type(ts_type)
    for ts_type in base_fields.values():
        module.validate_ts_type(ts_type)

    lines: list[str] = [GENERATED_HEADER, ""]

    # Named tool_calls element type (self-contained output).
    lines.append(f"export type {tool_call_type_name} = {{")
    for field_name, ts_type in tool_call_fields.items():
        lines.append(f"  {field_name}: {ts_type};")
    lines.append("};")
    lines.append("")

    # Per-wire-type interfaces (declaration order = WIRE_SCHEMA insertion order).
    # Wire shape is NESTED: { type; data: { ...event-fields..., trace_id? } }
    # mirroring sse.py serialize_loop_event + chatStore.ts ev.data.<field> reads.
    # Base fields (trace_id) are emitted OPTIONAL inside data: the serializer
    # carries trace_id on the wire, but in-process consumers / fixtures build
    # events without it (correlation metadata the UI never reads).
    for wire_type, fields in wire_schema.items():
        interface = _pascal_interface(wire_type)
        lines.append(f"export interface {interface} {{")
        lines.append(f'  type: "{wire_type}";')
        lines.append("  data: {")
        for field_name, ts_type in base_fields.items():
            lines.append(f"    {field_name}?: {ts_type};")
        for field_name, ts_type in fields.items():
            lines.append(f"    {field_name}: {ts_type};")
        lines.append("  };")
        lines.append("}")
        lines.append("")

    # LoopEvent union.
    union_members = [_pascal_interface(wire_type) for wire_type in wire_schema]
    lines.append("export type LoopEvent =")
    for index, member in enumerate(union_members):
        suffix = ";" if index == len(union_members) - 1 else ""
        lines.append(f"  | {member}{suffix}")
    lines.append("")

    # KNOWN_LOOP_EVENT_TYPES set (wire-type insertion order).
    lines.append("export const KNOWN_LOOP_EVENT_TYPES = new Set<string>([")
    for wire_type in wire_schema:
        lines.append(f'  "{wire_type}",')
    lines.append("]);")
    lines.append("")

    return "\n".join(lines)


def _normalize(text: str) -> str:
    """Normalize CRLF → LF for cross-platform diff comparison."""
    return text.replace("\r\n", "\n")


def _write(path: Path, content: str) -> None:
    """Write with explicit LF newlines (deterministic, cross-platform)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def _check_one(path: Path, expected: str) -> list[str]:
    """Return a unified-diff line list if `path` differs from `expected`, else []."""
    if not path.exists():
        return [f"MISSING generated file: {path}"]
    with open(path, encoding="utf-8") as handle:
        actual = _normalize(handle.read())
    expected_norm = _normalize(expected)
    if actual == expected_norm:
        return []
    rel = path.relative_to(REPO_ROOT).as_posix()
    return list(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected_norm.splitlines(keepends=True),
            fromfile=f"{rel} (committed)",
            tofile=f"{rel} (regenerated)",
        )
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify committed generated files match the registry; exit 1 on drift.",
    )
    args = parser.parse_args(argv)

    module = load_wire_schema()
    events_json = render_events_json(module)
    generated_ts = render_generated_ts(module)

    if args.check:
        diffs = _check_one(EVENTS_JSON_PATH, events_json) + _check_one(
            GENERATED_TS_PATH, generated_ts
        )
        if diffs:
            sys.stdout.write(
                "Event schema codegen drift detected. "
                "Run `python scripts/codegen/generate_event_schemas.py` and commit:\n"
            )
            sys.stdout.writelines(diffs)
            if not diffs[-1].endswith("\n"):
                sys.stdout.write("\n")
            return 1
        sys.stdout.write("Event schema codegen: generated files up to date.\n")
        return 0

    _write(EVENTS_JSON_PATH, events_json)
    _write(GENERATED_TS_PATH, generated_ts)
    sys.stdout.write(
        f"Wrote {EVENTS_JSON_PATH.relative_to(REPO_ROOT).as_posix()} + "
        f"{GENERATED_TS_PATH.relative_to(REPO_ROOT).as_posix()}\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
